# ======================== Getting All Users ========================
###
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZGFhNmYzNzNlODdkMzM4NzhmNWQ2YiIsImVtYWlsIjoiZXJpY3NvbkBnbWFpbC5jb20iLCJpYXQiOjE3MjU2MDYxNzYsImV4cCI6MTcyNTYwOTc3Nn0.OzT7T_NhBRMVyKP9SQok-V-0yCrtESsRKAzPukUi3Gs

# ======================== Creating a New User ========================
###
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "firstName": "Ericson",
    "lastName":"Palisoc",
    "email":"Ericson@gmail.com",
    "password":"Ericson123"
}

# ======================== Login User ========================
###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{ 
    "email":"Ericson@gmail.com",
    "password":"Ericson123"
}

# ======================== Update User ========================
###
PUT http://localhost:5000/api/users/66da9c424a83c0af61c1e2b9

Content-Type: application/json

{
    "firstName": "Ericson",
    "lastName": "Palisoc"
}

# ======================== Remove User ========================
###
DELETE http://localhost:5000/api/users/66daa5ba97feede33fbc1da8
Content-Type: application/json