# ======================== Getting All Users ========================

# GET http://localhost:5000/api/users

# ======================== Creating a New User ========================

# POST http://localhost:5000/api/users/register
# Content-Type: application/json

# {
#     "firstName": "Gina",
#     "lastName":"Palisoc",
#     "email":"Gina@gmail.com",
#     "password":"Gina123"
# }

# ======================== Login User ========================

# POST http://localhost:5000/api/users/login
# Content-Type: application/json

# { 
#     "email":"Ericson@gmail.com",
#     "password":"Ericson123"
# }

# ======================== Update User ========================

# PUT http://localhost:5000/api/users/66da9c424a83c0af61c1e2b9
# Content-Type: application/json

# {
#     "firstName": "Ericson",
#     "lastName": "Palisoc"
# }

# ======================== Remove User ========================

# DELETE http://localhost:5000/api/users/66da9c424a83c0af61c1e2b9
# Content-Type: application/json